#include "Sum/line.hpp"
#include "Sum/thread.hpp"
#include "Sum/hybrid.hpp"
#include "Sort/insertion.hpp"
#include "Sort/bubble.hpp"
#include "Sort/selection.hpp"
#include "Sort/merge.hpp"
#include "Sort/quick.hpp"